version: '3'
services: 
  cliente:
    image: cliente:latest
    container_name: cliente
    environment:
      - DISPLAY=192.168.0.12:0
    volumes:
      - C:\Users\Esteban:\Esteban  
    ports:
      - 22222:22222
    